### PR TITLE
Added Dockerfiles that fix dependancy problems for xslfo module

### PR DESCRIPTION
**Pull request by Sincopy**
Created two additional Dockerfiles, one for minified and one for full version of the image. They copy over dependencies missing in the distroless image from the openjdk:8-jdk-slim.

First section of files copied over should be enough for Apache FOP to do it's job, however in order to also support SVG rendering, the second set of files is also needed to fulfil dependencies for Apache Batik.

### CODE REVIEW

**Comment by adamretter** [comment]
@Sincopy Wow this looks great! I need to do a little reading and testing before merging, but I think enabling support for FOP could be the default.

Just wondering why the Travis-CI is failing for this though. Any thoughts?

**Comment by Sincopy** [comment]
FOP as default: makes sense from the perspective of xslfo module already being included in eXist by default, however I'm not sure if everyone needs it and the copied files add some size and the build pulls an additional image (build-time space requirements increase), so I left it as an option. I also fear things will break when the distroless image upgrades to newer versions of JRE.

About travis-ci: I was wondering the same thing, since it looks like it completes generating the image. I guess it doesn't like the removal of dangling images at the end (last line of the build.sh), which is not really needed, I guess. Btw. I noticed travis-ci is building on oracleJDK, while distroless is openJDK and it's building eXist 3.5.0, while current version is 3.6.1. Not sure if it's important, I guess not really, but perhaps worth considering.

**Comment by adamretter** [comment]
@sincopy Thanks for your changes. I am going to compare the sizes of the FOP and non-FOP builds, if the difference is minimal, then I will just switch to the fop ones.

**Comment by adamretter** [comment]
Okay so after building this is the size I am seeing:

```
evolvedbinary/exist-db    eXist-4.0.0-minimal-fop   ca9832fdbb37        2 minutes ago       291MB
evolvedbinary/exist-db    eXist-4.0.0-minimal       cd57a6cec486        About an hour ago   286MB
evolvedbinary/exist-db    eXist-4.0.0-fop           8d6008cb31e9        9 minutes ago       918MB
evolvedbinary/exist-db    eXist-4.0.0               0f24be876690        About an hour ago   913MB
```

As the difference between non-fop and fop support is only: 5MB. I am inclined to switch the default images to include support for FOP.

@Sincopy Thanks again for this excellent contribution :-)

**Pull request merged**
